version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo “Nothing to install for dependencies”
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws s3 cp * s3://rajadevops/ —-recursive 
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - index.html
  discard-paths: yes
